# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProfession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('prof_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='profession/')),
                ('money', models.IntegerField(default=0)),
                ('cat_key', models.IntegerField(default=0)),
                ('spec_1', models.ImageField(upload_to='profession/specs/')),
                ('spec_2', models.ImageField(upload_to='profession/specs/')),
                ('spec_3', models.ImageField(upload_to='profession/specs/')),
                ('spec_4', models.ImageField(upload_to='profession/specs/')),
                ('spec_5', models.ImageField(upload_to='profession/specs/')),
                ('spec_6', models.ImageField(upload_to='profession/specs/')),
                ('category_prof_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.CategoryProfession')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='study_program/')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='tests/')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='university/')),
                ('site_url', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('nums', models.IntegerField(default=0)),
                ('study_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.StudyProgram')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='study_program_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.StudyProgram'),
        ),
    ]
