# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='study_key',
        ),
        migrations.AddField(
            model_name='university',
            name='study_key',
            field=models.ManyToManyField(to='web.StudyProgram'),
        ),
    ]
