# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170723_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='univerisity_key',
            field=models.ManyToManyField(to='web.University'),
        ),
    ]
