# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profession_univerisity_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='univerisity_key',
        ),
        migrations.AddField(
            model_name='university',
            name='prof_key',
            field=models.ManyToManyField(to='web.Profession'),
        ),
    ]
