# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170723_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='biology',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='geography',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='informatics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='literature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='physic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='society',
            field=models.IntegerField(default=0),
        ),
    ]
