# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170727_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyprogram',
            old_name='physic',
            new_name='mathematics',
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='russian',
            field=models.IntegerField(default=0),
        ),
    ]
