# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_studyprogram_chemistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='biology',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='chemistry',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='english',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='geography',
            field=models.IntegerField(default=37),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='history',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='informatics',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='literature',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='mathematics',
            field=models.IntegerField(default=27),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='physics',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='russian',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='society',
            field=models.IntegerField(default=42),
        ),
    ]
