# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170803_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
